### ISSUE TITLE
Event Point Extractor

### ISSUE THREAD

**Issue by konstantin-sancom** [JorenSix/Olaf#10]
`src/olaf_ep_extractor.c:152`

`void rotate(Olaf_EP_Extractor * ep_extractor){`

`ep_extractor->maxes[i-1]=ep_extractor->maxes[i];`
`ep_extractor->mags[i-1]=ep_extractor->mags[i];`

Is there a `pointer` to array row assignment or you meaned `array row values` assigment?

**Comment by JorenSix** [comment]
The idea here is to 'rotate' the 2d array. 
In the way I understand it an array can be interpreted as a pointer to a memory block. A 2d array is a list of pointers to  memory blocks. Here the pointers are shifted by one. So no value assignments.
