### ISSUE TITLE
Comparing short audio files

### ISSUE THREAD

**Issue by galarlo** [JorenSix/Olaf#19]
Hi,
I'm interested in finding near-duplicate audio files. My dataset is about 3000 thousands short audio files, between 0.5 seconds to 5 seconds. Unlike Shazam, both the "target" audio (i.e. the songs in Shazam's case) and the user input are short, and both might contain noise.

Can this library help?
If so, are there any recommendations for tuning parameters?

N.B - if a file is matched to multiple other files, it's fine - I have a less efficient algorithm that can verify which match is correct. In other words, I can handle some amount of false positives, but I don't want false negatives.

**Comment by JorenSix** [comment]
Hi the main recommendation would be to allow more fingerprints per second using the configuration options. This can be done by allowing more event points by modifying the filter sizes in both frequency as in time axis:
<code>
config->filterSizeFrequency=51;//frequency bins 
config->halfFilterSizeFrequency=config->filterSizeFrequency/2;

config->filterSizeTime=13;
config->halfFilterSizeTime=config->filterSizeTime/2
</code>
