### ISSUE TITLE
example on esp32

### ISSUE THREAD

**Issue by geerdkakes** [JorenSix/Olaf#2]
Hi, do you also have an example how to run this on an esp32?

**Comment by JorenSix** [comment]
I do, it requires a bit of plumbing to get it working: you need a I2S digital microphone to get audio and need to transfer that into Olaf. That code is quite dependent on which components (microcontroller, microphone) and pins. You also might need to hack Olaf to get the required reaction upon recognition, which is also very dependent on specifics. On the whole this makes the code much less reusable and not very interesting to share.

However I have attached a PlatformIO ESP32 project to the "Olaf blog post":https://0110.be/posts/Olaf_-_Acoustic_fingerprinting_on_the_ESP32_and_in_the_Browser or "here":https://0110.be/files/attachments/475/ESP32-Olaf.zip
