### ISSUE TITLE
Question: Why C and not C++?

### ISSUE THREAD

**Issue by konstantin-sancom** [JorenSix/Olaf#20]
Hi, @JorenSix 

Why is this project written in C and not in C++?
In source code I see some imitation of C++ classes, like in "Perl".

**Comment by JorenSix** [comment]
Hi I like the portability, backwards compatibility, and above all simplicity of C. C is something I can still get my head around. 

C++ has evolved into a language which, arguably, nobody fully masters. The c code is indeed inspired by object-oriented principles and uses ideas of e.g. interface based programming.
