### ISSUE TITLE
Missing/limited instructions for running tests

### ISSUE THREAD

**Issue by liscio** [JorenSix/Olaf#25]
I think it would be helpful if users/contributors had instructions for running the automated tests locally when possible. The README makes reference to the scripts in the `eval/` directory, but it's not clear how to use them, when contributors should execute certain tests, and so on.

Similarly, there appears to be a `test` target in the Makefile that claims to "build and test" olaf, but no test is actually executed. If this is intended to be part of the testing suite, it'd be a good idea to include that in the README as well.

Related to: https://github.com/openjournals/joss-reviews/issues/5459

**Comment by JorenSix** [comment]
The readme has been extended with instructions to run the unit tests and the functional tests. 
The readme is already a bit long to my tastes. Perhaps it needs some more attention to structure it better (the order of headers is a bit random now...).
