### ISSUE TITLE
Missing square brackets around references.

### ISSUE THREAD

**Issue by ebezzam** [JorenSix/Olaf#35]
Related to: https://github.com/openjournals/joss-reviews/issues/5459

https://github.com/JorenSix/Olaf/blob/0173ff18411294ea0577569e6cbd52dbad8fd85d/paper.md?plain=1#L34

https://github.com/JorenSix/Olaf/blob/0173ff18411294ea0577569e6cbd52dbad8fd85d/paper.md?plain=1#L40

**Comment by JorenSix** [comment]
There is a deliberate formatting difference when using square brackets or not. In some cases the references are meant to fit in the text. 

For example "a paper by Fenet et al (2020)" is without brackets while "there are a number of papers on blablabla [Fenet 2020; Wang 2003]" is with brackets.

**Comment by ebezzam** [comment]
Got it, could you still format the citation for "Cortes et. al, 2022" entry so that it's like the others? The long list of names on lines 41-42 and 51-52 is a but awkward.

**Comment by JorenSix** [comment]
Fixed, the problem was the use of `authors = {{author list}}`. With this formatting the author list is used literally, when using `authors = {author list}` it is correctly replaced by an 'et al'.
