### ISSUE TITLE
Generating fingerprints for ESP32

### ISSUE THREAD

**Issue by hippiefm** [JorenSix/Olaf#6]
Hi,

I am developing an application which communicates with external device and it should be able to perform diagnostics on this device according to sound made by it. I found your project today and I thought it fits ideally in my needs, however I have some serious problems with running it.

I am using ESP32 as my platform with I2S microphone (it is already working), so I wanted to build OLAF Mem version. It succeeded, but calling `./olaf_mem store sample.mp3 wav 666` generates following output:

`Stored 0 fp's from 16.8s in 0.108s (156 times realtime)`

I think that Ruby script is responsible for generating fingerprints, however I don't know how to use it correctly. Of course both `ruby` and `ffmpeg` are in my PATH.

Are you able to help me with generating fingerprints?

**Comment by JorenSix** [comment]
Hi 
Can you try again with the current version?
